### ISSUE TITLE
Show popular posts

### ISSUE THREAD

**Issue by Sogl** [Perlkonig/grav-plugin-count-views#6]
Hello!

I want to use this plugin to show popular posts but don't know how 😄 
If I type:
```
{{ dump(viewcounts) }}
```
then I see full list of routes and counts.

But I want to use something like that:
```
content:
    items: @self.children
    order:
        by: viewcounts
        dir: desc
```

Any ideas?
